import 'dart:io';

import 'config.dart';
import 'result.dart';

/// Build-time app info generator.
///
/// Only `pubspec.yaml` is required. Android-specific metadata is picked up
/// when the host project also contains:
/// - `android/app/src/main/AndroidManifest.xml` → `appName`
/// - `android/app/build.gradle.kts` → `packageName`
///
/// On non-Android host projects (iOS/macOS/Linux/Windows-only) those files
/// are absent and the generator emits cross-platform fields only, with safe
/// defaults for the Android-specific ones.
class AppInfoGenerator {
  static const String toolName = 'app_info_builder';
  static const String toolVersion = '0.0.2';

  /// Generate file app_info.dart from [projectRoot].
  ///
  /// Throw [AppInfoGenerationException] only when `pubspec.yaml` is missing.
  static AppInfoResult generate({
    required Directory projectRoot,
    AppInfoConfig config = const AppInfoConfig(),
  }) {
    final root = projectRoot.absolute.path;
    final sources = <String>[];

    // 1. Version + build number from pubspec.yaml (required, cross-platform)
    final pubspecFile = File('$root/pubspec.yaml');
    if (!pubspecFile.existsSync()) {
      throw AppInfoGenerationException(
        'pubspec.yaml not found at ${pubspecFile.path}',
      );
    }
    sources.add('pubspec.yaml');
    final pubspecContent = pubspecFile.readAsStringSync();
    final versionMatch =
        RegExp(r'^version:\s*(\S+)', multiLine: true)
            .firstMatch(pubspecContent);
    final versionString = versionMatch?.group(1) ?? '0.0.0+0';
    final versionParts = versionString.split('+');
    final version = versionParts[0];
    final buildNumber = versionParts.length > 1 ? versionParts[1] : '0';
    final fullVersion = '$version+$buildNumber';

    // 2. App name from AndroidManifest.xml (optional, Android-only)
    final manifestFile =
        File('$root/android/app/src/main/AndroidManifest.xml');
    String appName = 'Unknown';
    if (manifestFile.existsSync()) {
      sources.add('AndroidManifest.xml');
      final manifestContent = manifestFile.readAsStringSync();
      final labelMatch = RegExp(r'android:label\s*=\s*"([^"]*)"')
          .firstMatch(manifestContent);
      appName = labelMatch?.group(1) ?? 'Unknown';
    }

    // 3. Package name from build.gradle.kts (optional, Android-only)
    String packageName = config.packageNameOverride ?? 'com.example.unknown';
    if (config.packageNameOverride == null) {
      final gradleFile = File('$root/android/app/build.gradle.kts');
      if (gradleFile.existsSync()) {
        sources.add('build.gradle.kts');
        final gradleContent = gradleFile.readAsStringSync();
        final applicationIdMatch = RegExp(r'applicationId\s*=\s*"([^"]+)"')
            .firstMatch(gradleContent);
        final namespaceMatch =
            RegExp(r'namespace\s*=\s*"([^"]+)"').firstMatch(gradleContent);
        packageName = applicationIdMatch?.group(1) ??
            namespaceMatch?.group(1) ??
            'com.example.unknown';
      }
    }

    // 4. Optional git hash
    String? gitHash;
    if (config.includeGitHash) {
      gitHash = _readGitHash(projectRoot);
    }

    // 5. Optional build timestamp
    String? buildTimestamp;
    if (config.includeBuildTimestamp) {
      buildTimestamp = DateTime.now().toUtc().toIso8601String();
    }

    // 6. Build the Dart source
    final content = _buildDartContent(
      className: config.className,
      sources: sources,
      appName: appName,
      packageName: packageName,
      version: version,
      buildNumber: buildNumber,
      fullVersion: fullVersion,
      gitHash: gitHash,
      buildTimestamp: buildTimestamp,
      extraFields: config.extraFields,
    );

    // 7. Write the file
    final outputFile = File('$root/${config.outputPath}');
    outputFile.parent.createSync(recursive: true);
    outputFile.writeAsStringSync(content);

    return AppInfoResult(
      outputPath: outputFile.path,
      className: config.className,
      appName: appName,
      packageName: packageName,
      version: version,
      buildNumber: buildNumber,
      fullVersion: fullVersion,
      gitHash: gitHash,
      buildTimestamp: buildTimestamp,
    );
  }

  static String _buildDartContent({
    required String className,
    required List<String> sources,
    required String appName,
    required String packageName,
    required String version,
    required String buildNumber,
    required String fullVersion,
    String? gitHash,
    String? buildTimestamp,
    required Map<String, String> extraFields,
  }) {
    final buf = StringBuffer()
      ..writeln('// GENERATED FILE — DO NOT MODIFY')
      ..writeln('// Generated by $toolName v$toolVersion')
      ..writeln('// Source: ${sources.join(', ')}')
      ..writeln()
      ..writeln('/// Compile-time application metadata.')
      ..writeln('/// Regenerated at build time by the app_info_builder native build hook.')
      ..writeln('class $className {')
      ..writeln("  static const String appName = '${_escape(appName)}';")
      ..writeln("  static const String packageName = '${_escape(packageName)}';")
      ..writeln("  static const String version = '${_escape(version)}';")
      ..writeln("  static const String buildNumber = '${_escape(buildNumber)}';")
      ..writeln("  static const String fullVersion = '${_escape(fullVersion)}';");

    if (gitHash != null) {
      buf.writeln("  static const String gitHash = '${_escape(gitHash)}';");
    }
    if (buildTimestamp != null) {
      buf.writeln(
          "  static const String buildTimestamp = '${_escape(buildTimestamp)}';");
    }

    extraFields.forEach((key, value) {
      buf.writeln("  static const String $key = '${_escape(value)}';");
    });

    buf
      ..writeln()
      ..writeln('  const $className._();')
      ..writeln('}');

    return buf.toString();
  }

  static String _escape(String s) =>
      s.replaceAll(r'\', r'\\').replaceAll("'", r"\'").replaceAll(r'$', r'\$');

  static String? _readGitHash(Directory projectRoot) {
    try {
      final result = Process.runSync(
        'git',
        ['rev-parse', '--short', 'HEAD'],
        workingDirectory: projectRoot.path,
      );
      if (result.exitCode == 0) {
        return (result.stdout as String).trim();
      }
    } catch (_) {
      // git not available / not a git repo — leave null
    }
    return null;
  }
}

class AppInfoGenerationException implements Exception {
  final String message;
  const AppInfoGenerationException(this.message);

  @override
  String toString() => 'AppInfoGenerationException: $message';
}
