/// Build-time app info generator for Flutter projects.
///
/// Reads `pubspec.yaml` (cross-platform) and, when present, the Android
/// manifest / Gradle files, then writes a Dart file containing compile-time
/// constants — ready to use without runtime lookup.
///
/// The file is regenerated by a build hook in the host project's native
/// build system — Gradle on Android, CocoaPods `script_phase` on iOS/macOS,
/// CMake on Linux/Windows — all of which call the same CLI:
/// `dart run app_info_builder:generate`.
library;

export 'src/config.dart';
export 'src/generator.dart';
export 'src/result.dart';
