// Smoke test for example_app — verifies that the home screen displays
// the fields generated by app_info_builder.

import 'package:flutter_test/flutter_test.dart';
import 'package:example_app/main.dart';
import 'package:example_app/generated/app_info.dart';

void main() {
  testWidgets('home screen shows metadata generated by app_info_builder',
      (WidgetTester tester) async {
    await tester.pumpWidget(const MyApp());

    // Required fields — must be visible in the UI.
    expect(find.text('appName'), findsOneWidget);
    expect(find.text(ExampleAppInfo.appName), findsOneWidget);
    expect(find.text('packageName'), findsOneWidget);
    expect(find.text(ExampleAppInfo.packageName), findsOneWidget);
    expect(find.text('fullVersion'), findsOneWidget);
    expect(find.text(ExampleAppInfo.fullVersion), findsOneWidget);
  });

  test('generated constants are not empty', () {
    expect(ExampleAppInfo.appName, isNotEmpty);
    expect(ExampleAppInfo.packageName, isNotEmpty);
    expect(ExampleAppInfo.version, isNotEmpty);
    expect(ExampleAppInfo.buildNumber, isNotEmpty);
    expect(ExampleAppInfo.fullVersion, contains('+'));
  });
}
